spring:
  h2:    console:
      path: /h2-console      enabled: true
  jpa:
    properties:      hibernate:
        format_sql: true    show-sql: true
  datasource:    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:changelog.xml
    enabled: true  