spring:
  datasource:
    jndi-name: java:/BRTMP
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: false