spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: calendar
    password: calendar
    driver-class-name: oracle.jdbc.OracleDriver
  application:
    name: apitemplate
  jmx:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        proc:
          param_null_passing: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:changelog.xml
    enabled: true
    liquibase-schema: calendar
  output:
    ansi:
      enabled: ALWAYS
  profiles:    active: activeProfile@        
