
CREATE TABLE "COUNTRY"
(
    "ID" NUMBER(3,0) NOT NULL,
    "NAME" VARCHAR2(100) NOT NULL,
    "CODE" CHAR(2),
    "ACTIVE" CHAR(1) NOT NULL, 
    "CREATION_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    "HAS_STATE" CHAR(1),
    CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID")
);
CREATE SEQUENCE COUNTRY_PK START WITH 1;

CREATE TABLE "STATE"
(
    "ID" NUMBER(10,0) NOT NULL,
    "COUNTRY_ID" NUMBER(3,0) NOT NULL,
    "NAME" VARCHAR2(150) NOT NULL,
    "CODE" CHAR(2),
    "ACTIVE" CHAR(1) NOT NULL,
    "CREATION_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    CONSTRAINT "STATE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_STATE_COUNTRY" FOREIGN KEY ("COUNTRY_ID")
    REFERENCES "COUNTRY" ("ID")
);

CREATE SEQUENCE STATE_PK START WITH 1;

CREATE TABLE "CITY"
(
    "ID" NUMBER(10,0) NOT NULL,
    "STATE_ID" NUMBER(10,0),
    "NAME" VARCHAR2(150) NOT NULL,
    "ACTIVE" CHAR(1) NOT NULL,
    "CREATION_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    "COUNTRY_ID" NUMBER(3,0),
    CONSTRAINT "CITY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CITY_STATE" FOREIGN KEY ("STATE_ID")
    REFERENCES "STATE" ("ID"),
    CONSTRAINT "FK_CITY_COUNTRY" FOREIGN KEY ("COUNTRY_ID")
    REFERENCES "COUNTRY" ("ID")
);

CREATE SEQUENCE CITY_PK START WITH 1;

CREATE TABLE "HOLLIDAY" 
(
    "ID" NUMBER(5,0) NOT NULL,
    "NAME" VARCHAR2(150) NOT NULL,
    "ACTIVE" CHAR(1) NOT NULL,
    "CREATION_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    CONSTRAINT "HOLLIDAY_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE HOLLIDAY_PK START WITH 1;

CREATE TABLE "HOLLIDAY_DATE" 
(
    "COUNTRY_ID" NUMBER(3,0) NOT NULL,
    "STATE_ID" NUMBER(10,0),
    "CITY_ID" NUMBER(10,0),
    "HOLLIDAY_ID" NUMBER(5,0) NOT NULL,
    "DAY" NUMBER(2,0) NOT NULL,
    "MONTH" NUMBER(2,0) NOT NULL,
    "YEAR" NUMBER(4,0),
    "ACTIVE" CHAR(1) NOT NULL,
    "CREATION_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP, 
    CONSTRAINT "FK_HOLLIDAY_DATE_COUNTRY" FOREIGN KEY ("COUNTRY_ID")
    REFERENCES "COUNTRY" ("ID"), 
    CONSTRAINT "FK_HOLLIDAY_DATE_STATE" FOREIGN KEY ("STATE_ID")
    REFERENCES "STATE" ("ID"), 
    CONSTRAINT "FK_HOLLIDAY_DATE_CITY" FOREIGN KEY ("CITY_ID")
    REFERENCES "CITY" ("ID"), 
    CONSTRAINT "FK_HOLLIDAY_DATE_HOLLIDAY" FOREIGN KEY ("HOLLIDAY_ID")
    REFERENCES "HOLLIDAY" ("ID")
);